<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AssignedProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('assigned_products')->delete();
        
        \DB::table('assigned_products')->insert(array (
            0 => 
            array (
                'id' => 15,
                'type' => 'purchase',
                'model_id' => 10,
                'product_id' => 7,
                'amount_type' => 'cost',
                'product_amount' => 250,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:54:10',
                'updated_at' => '2023-03-31 19:54:10',
            ),
            1 => 
            array (
                'id' => 16,
                'type' => 'purchase',
                'model_id' => 11,
                'product_id' => 7,
                'amount_type' => 'cost',
                'product_amount' => 250,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:56:18',
                'updated_at' => '2023-03-31 19:56:18',
            ),
            2 => 
            array (
                'id' => 17,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 5,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            3 => 
            array (
                'id' => 18,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 5,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            4 => 
            array (
                'id' => 19,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 3,
                'amount_type' => 'cost',
                'product_amount' => 200000,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            5 => 
            array (
                'id' => 20,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 4,
                'amount_type' => 'cost',
                'product_amount' => 20,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            6 => 
            array (
                'id' => 21,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 5,
                'amount_type' => 'cost',
                'product_amount' => 170,
                'base_unit_id' => 13,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            7 => 
            array (
                'id' => 22,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 6,
                'amount_type' => 'cost',
                'product_amount' => 200,
                'base_unit_id' => 13,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            8 => 
            array (
                'id' => 23,
                'type' => 'purchase',
                'model_id' => 12,
                'product_id' => 11,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            9 => 
            array (
                'id' => 24,
                'type' => 'purchase',
                'model_id' => 13,
                'product_id' => 12,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 11,
                'quantity' => 10,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-03-31 21:36:26',
                'updated_at' => '2023-03-31 21:36:26',
            ),
            10 => 
            array (
                'id' => 25,
                'type' => 'purchase',
                'model_id' => 15,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 5,
                'quantity' => 21,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-01 21:21:21',
                'updated_at' => '2023-04-01 21:21:21',
            ),
            11 => 
            array (
                'id' => 28,
                'type' => 'purchase',
                'model_id' => 17,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 12,
                'quantity' => 4,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 18:05:26',
                'updated_at' => '2023-04-02 18:05:26',
            ),
            12 => 
            array (
                'id' => 29,
                'type' => 'purchase',
                'model_id' => 18,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 12,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 18:08:04',
                'updated_at' => '2023-04-02 18:08:04',
            ),
            13 => 
            array (
                'id' => 30,
                'type' => 'purchase',
                'model_id' => 19,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 5,
                'quantity' => 20,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 18:09:54',
                'updated_at' => '2023-04-02 18:09:54',
            ),
            14 => 
            array (
                'id' => 31,
                'type' => 'purchase',
                'model_id' => 20,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 20:21:41',
                'updated_at' => '2023-04-02 20:21:41',
            ),
            15 => 
            array (
                'id' => 32,
                'type' => 'purchase',
                'model_id' => 21,
                'product_id' => 12,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 9,
                'quantity' => 9,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 20:29:00',
                'updated_at' => '2023-04-02 20:29:00',
            ),
            16 => 
            array (
                'id' => 34,
                'type' => 'purchase',
                'model_id' => 23,
                'product_id' => 11,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 20:53:42',
                'updated_at' => '2023-04-02 20:53:42',
            ),
            17 => 
            array (
                'id' => 35,
                'type' => 'purchase',
                'model_id' => 23,
                'product_id' => 6,
                'amount_type' => 'cost',
                'product_amount' => 200,
                'base_unit_id' => 13,
                'quantity' => 2,
                'discount_type' => 'fixed',
                'discount' => 10,
                'created_at' => '2023-04-02 20:53:42',
                'updated_at' => '2023-04-02 20:53:42',
            ),
            18 => 
            array (
                'id' => 36,
                'type' => 'purchase',
                'model_id' => 23,
                'product_id' => 5,
                'amount_type' => 'cost',
                'product_amount' => 170,
                'base_unit_id' => 13,
                'quantity' => 3,
                'discount_type' => 'percentage',
                'discount' => 20,
                'created_at' => '2023-04-02 20:53:42',
                'updated_at' => '2023-04-02 20:53:42',
            ),
            19 => 
            array (
                'id' => 53,
                'type' => 'purchase',
                'model_id' => 24,
                'product_id' => 12,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 21:14:50',
                'updated_at' => '2023-04-02 21:14:50',
            ),
            20 => 
            array (
                'id' => 54,
                'type' => 'purchase',
                'model_id' => 24,
                'product_id' => 10,
                'amount_type' => 'cost',
                'product_amount' => 70,
                'base_unit_id' => 11,
                'quantity' => 3,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 21:14:50',
                'updated_at' => '2023-04-02 21:14:50',
            ),
            21 => 
            array (
                'id' => 55,
                'type' => 'purchase',
                'model_id' => 24,
                'product_id' => 9,
                'amount_type' => 'cost',
                'product_amount' => 400,
                'base_unit_id' => 11,
                'quantity' => 3,
                'discount_type' => 'fixed',
                'discount' => 10,
                'created_at' => '2023-04-02 21:14:50',
                'updated_at' => '2023-04-02 21:14:50',
            ),
            22 => 
            array (
                'id' => 56,
                'type' => 'purchase',
                'model_id' => 24,
                'product_id' => 7,
                'amount_type' => 'cost',
                'product_amount' => 250,
                'base_unit_id' => 8,
                'quantity' => 9,
                'discount_type' => 'percentage',
                'discount' => 20,
                'created_at' => '2023-04-02 21:14:50',
                'updated_at' => '2023-04-02 21:14:50',
            ),
            23 => 
            array (
                'id' => 75,
                'type' => 'purchase',
                'model_id' => 22,
                'product_id' => 12,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 22:06:56',
                'updated_at' => '2023-04-02 22:06:56',
            ),
            24 => 
            array (
                'id' => 76,
                'type' => 'purchase',
                'model_id' => 22,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 5,
                'quantity' => 8,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 22:06:56',
                'updated_at' => '2023-04-02 22:06:56',
            ),
            25 => 
            array (
                'id' => 77,
                'type' => 'purchase',
                'model_id' => 16,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 5,
                'quantity' => 5,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 22:07:38',
                'updated_at' => '2023-04-02 22:07:38',
            ),
            26 => 
            array (
                'id' => 78,
                'type' => 'purchase',
                'model_id' => 16,
                'product_id' => 2,
                'amount_type' => 'cost',
                'product_amount' => 100,
                'base_unit_id' => 12,
                'quantity' => 3,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-02 22:07:38',
                'updated_at' => '2023-04-02 22:07:38',
            ),
            27 => 
            array (
                'id' => 80,
                'type' => 'purchase',
                'model_id' => 26,
                'product_id' => 5,
                'amount_type' => 'cost',
                'product_amount' => 170,
                'base_unit_id' => 13,
                'quantity' => 4,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-03 20:24:19',
                'updated_at' => '2023-04-03 20:24:19',
            ),
            28 => 
            array (
                'id' => 86,
                'type' => 'purchase',
                'model_id' => 27,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 5,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-03 21:19:51',
                'updated_at' => '2023-04-03 21:19:51',
            ),
            29 => 
            array (
                'id' => 87,
                'type' => 'purchase',
                'model_id' => 27,
                'product_id' => 3,
                'amount_type' => 'cost',
                'product_amount' => 200000,
                'base_unit_id' => 11,
                'quantity' => 2,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-03 21:19:51',
                'updated_at' => '2023-04-03 21:19:51',
            ),
            30 => 
            array (
                'id' => 88,
                'type' => 'purchase',
                'model_id' => 27,
                'product_id' => 5,
                'amount_type' => 'cost',
                'product_amount' => 170,
                'base_unit_id' => 13,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-03 21:19:51',
                'updated_at' => '2023-04-03 21:19:51',
            ),
            31 => 
            array (
                'id' => 89,
                'type' => 'purchase',
                'model_id' => 27,
                'product_id' => 11,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 11,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-03 21:19:51',
                'updated_at' => '2023-04-03 21:19:51',
            ),
            32 => 
            array (
                'id' => 91,
                'type' => 'purchase',
                'model_id' => 28,
                'product_id' => 1,
                'amount_type' => 'cost',
                'product_amount' => 50,
                'base_unit_id' => 5,
                'quantity' => 1,
                'discount_type' => 'fixed',
                'discount' => 0,
                'created_at' => '2023-04-04 11:38:59',
                'updated_at' => '2023-04-04 11:38:59',
            ),
        ));
        
        
    }
}