<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'currency_id' => 2,
                'name' => 'Pagah cheese',
                'code' => '0B202001020$09',
                'image' => NULL,
                'brand_id' => 10,
                'product_category_id' => 5,
                'barcode_symbology' => 39,
                'price' => 55,
                'cost' => 50,
                'product_unit_id' => 6,
                'product_sale_unit_id' => 5,
                'product_purchase_unit_id' => 5,
                'stock_alert' => 20,
                'note' => '<p>This is the note</p>',
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-18 18:07:00',
                'updated_at' => '2023-03-21 17:40:38',
            ),
            1 => 
            array (
                'id' => 2,
                'currency_id' => 2,
                'name' => 'Pizza cheese',
                'code' => '0B202001020$092',
                'image' => 'http://127.0.0.1:8000/storage/product_images/RA4HPu2DvTCifKQcAvNVcN8TSUGpogQlUlBeSrgv.jpg',
                'brand_id' => 10,
                'product_category_id' => 5,
                'barcode_symbology' => 39,
                'price' => 101,
                'cost' => 100,
                'product_unit_id' => 5,
                'product_sale_unit_id' => 5,
                'product_purchase_unit_id' => 5,
                'stock_alert' => 20,
                'note' => '<p>Test</p>',
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-18 19:14:38',
                'updated_at' => '2023-03-18 19:14:38',
            ),
            2 => 
            array (
                'id' => 3,
                'currency_id' => 2,
                'name' => 'Caw cheese',
                'code' => '0B2010001010A',
                'image' => 'http://127.0.0.1:8000/storage/product_images/a88WELnrBlrmQe5xk3ihrXtahxGUXlzdEtvCdO99.png',
                'brand_id' => 10,
                'product_category_id' => 5,
                'barcode_symbology' => 39,
                'price' => 200001,
                'cost' => 200000,
                'product_unit_id' => 5,
                'product_sale_unit_id' => 5,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 30,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-18 19:45:08',
                'updated_at' => '2023-03-22 10:52:55',
            ),
            3 => 
            array (
                'id' => 4,
                'currency_id' => 3,
                'name' => 'Qwat milk',
                'code' => '8681038133872',
                'image' => 'http://127.0.0.1:8000/storage/product_images/LCzOPReaRIRKquMXqoOvOt0w3j8JGm57w0jVsv7P.png',
                'brand_id' => 11,
                'product_category_id' => 5,
                'barcode_symbology' => 128,
                'price' => 30,
                'cost' => 20,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 11,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 20,
                'note' => '<p><br></p>',
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-20 17:43:56',
                'updated_at' => '2023-03-27 16:57:58',
            ),
            4 => 
            array (
                'id' => 5,
                'currency_id' => 2,
                'name' => 'FOGG spray',
                'code' => '8904238301958',
                'image' => NULL,
                'brand_id' => 13,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 200,
                'cost' => 170,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 11,
                'product_purchase_unit_id' => 13,
                'stock_alert' => 20,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:27:23',
                'updated_at' => '2023-03-28 17:27:23',
            ),
            5 => 
            array (
                'id' => 6,
                'currency_id' => 2,
                'name' => 'NIVEA cream',
                'code' => '4005808166190',
                'image' => NULL,
                'brand_id' => 14,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 220,
                'cost' => 200,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 11,
                'product_purchase_unit_id' => 13,
                'stock_alert' => 20,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:29:31',
                'updated_at' => '2023-03-28 17:29:31',
            ),
            6 => 
            array (
                'id' => 7,
                'currency_id' => 2,
                'name' => 'Hair food',
                'code' => '8901726954009',
                'image' => NULL,
                'brand_id' => 15,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 300,
                'cost' => 250,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 13,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 20,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:31:48',
                'updated_at' => '2023-03-28 17:31:48',
            ),
            7 => 
            array (
                'id' => 8,
                'currency_id' => 2,
                'name' => 'Pertroleum Jelly',
                'code' => '8906019550036',
                'image' => NULL,
                'brand_id' => 16,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 150,
                'cost' => 100,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 13,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 10,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:33:55',
                'updated_at' => '2023-03-28 17:33:55',
            ),
            8 => 
            array (
                'id' => 9,
                'currency_id' => 2,
                'name' => 'Eau de tolette natural spray vaporisateur',
                'code' => '5978170220595',
                'image' => NULL,
                'brand_id' => 17,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 500,
                'cost' => 400,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 11,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 10,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:36:51',
                'updated_at' => '2023-03-28 17:36:51',
            ),
            9 => 
            array (
                'id' => 10,
                'currency_id' => 2,
                'name' => 'Blue canal',
                'code' => '3587925368035',
                'image' => NULL,
                'brand_id' => 18,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 100,
                'cost' => 70,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 13,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 10,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:43:03',
                'updated_at' => '2023-03-28 17:43:03',
            ),
            10 => 
            array (
                'id' => 11,
                'currency_id' => 2,
                'name' => 'Air freshener',
                'code' => '3571700296637',
                'image' => NULL,
                'brand_id' => 19,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 100,
                'cost' => 50,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 13,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 20,
                'note' => '<p>This is note</p>',
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:44:39',
                'updated_at' => '2023-03-28 17:44:39',
            ),
            11 => 
            array (
                'id' => 12,
                'currency_id' => 2,
                'name' => 'Fresh active',
                'code' => '4005900088062',
                'image' => NULL,
                'brand_id' => 14,
                'product_category_id' => 7,
                'barcode_symbology' => 128,
                'price' => 150,
                'cost' => 100,
                'product_unit_id' => 11,
                'product_sale_unit_id' => 13,
                'product_purchase_unit_id' => 11,
                'stock_alert' => 20,
                'note' => NULL,
                'is_deleted' => 0,
                'status' => 'received',
                'created_at' => '2023-03-28 17:46:30',
                'updated_at' => '2023-03-28 17:46:30',
            ),
        ));
        
        
    }
}