<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PurchasesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchases')->delete();
        
        \DB::table('purchases')->insert(array (
            0 => 
            array (
                'id' => 10,
                'purchase_date' => '2023/03/31',
                'warehouse_id' => 3,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 250,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-03-31 19:54:10',
                'updated_at' => '2023-03-31 19:54:10',
            ),
            1 => 
            array (
                'id' => 11,
                'purchase_date' => '2023/03/31',
                'warehouse_id' => 3,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 250,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-03-31 19:56:18',
                'updated_at' => '2023-03-31 19:56:18',
            ),
            2 => 
            array (
                'id' => 12,
                'purchase_date' => '2023/03/31',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 30,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 10,
                'shipping' => 100,
                'grand_total' => 180648,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-03-31 19:58:51',
                'updated_at' => '2023-03-31 19:58:51',
            ),
            3 => 
            array (
                'id' => 13,
                'purchase_date' => '2023/03/31',
                'warehouse_id' => 3,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 1000,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-03-31 21:36:26',
                'updated_at' => '2023-03-31 21:36:26',
            ),
            4 => 
            array (
                'id' => 15,
                'purchase_date' => '2023/04/01',
                'warehouse_id' => 2,
                'supplier_id' => 2,
                'order_tax' => 7,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 3,
                'shipping' => 2,
                'grand_total' => 1027,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-01 21:21:21',
                'updated_at' => '2023-04-01 21:21:21',
            ),
            5 => 
            array (
                'id' => 16,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 550,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 14:22:45',
                'updated_at' => '2023-04-02 22:07:38',
            ),
            6 => 
            array (
                'id' => 17,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 200,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 18:05:26',
                'updated_at' => '2023-04-02 18:05:26',
            ),
            7 => 
            array (
                'id' => 18,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 100,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 18:08:04',
                'updated_at' => '2023-04-02 18:08:04',
            ),
            8 => 
            array (
                'id' => 19,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 2000,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 18:09:54',
                'updated_at' => '2023-04-02 18:09:54',
            ),
            9 => 
            array (
                'id' => 20,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 100,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 20:21:41',
                'updated_at' => '2023-04-02 20:21:41',
            ),
            10 => 
            array (
                'id' => 21,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 3,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 900,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 20:29:00',
                'updated_at' => '2023-04-02 20:29:00',
            ),
            11 => 
            array (
                'id' => 22,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 3,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 900,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 20:36:59',
                'updated_at' => '2023-04-02 22:06:56',
            ),
            12 => 
            array (
                'id' => 23,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 10,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 10,
                'shipping' => 10,
                'grand_total' => 781,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 20:53:42',
                'updated_at' => '2023-04-02 20:53:42',
            ),
            13 => 
            array (
                'id' => 24,
                'purchase_date' => '2023/04/02',
                'warehouse_id' => 3,
                'supplier_id' => 2,
                'order_tax' => 14,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 41,
                'shipping' => 31,
                'grand_total' => 1974,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-02 20:55:42',
                'updated_at' => '2023-04-02 21:14:50',
            ),
            14 => 
            array (
                'id' => 26,
                'purchase_date' => '2023/04/03',
                'warehouse_id' => 2,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 580,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-03 20:24:19',
                'updated_at' => '2023-04-03 21:23:10',
            ),
            15 => 
            array (
                'id' => 27,
                'purchase_date' => '2023/04/03',
                'warehouse_id' => 2,
                'supplier_id' => 2,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 400261,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-03 20:40:07',
                'updated_at' => '2023-04-03 21:22:49',
            ),
            16 => 
            array (
                'id' => 28,
                'purchase_date' => '2023/04/04',
                'warehouse_id' => 2,
                'supplier_id' => 1,
                'order_tax' => 0,
                'payment_type_id' => 3,
                'currency_id' => 2,
                'discount' => 0,
                'shipping' => 0,
                'grand_total' => 50,
                'due' => 0,
                'status' => 'received',
                'created_at' => '2023-04-04 11:15:10',
                'updated_at' => '2023-04-04 11:38:59',
            ),
        ));
        
        
    }
}